### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by abelramos** [moses-palmer/virtual-touchpad#1]
I am getting an error after sudo ./setup.py install

running install
running bdist_egg
running minify_help
Failed to minify SVG ./lib/virtualtouchpad/html/img/fullscreen-on.svg: python: can't open file './lib/build/../../scour/scour/scour.py': [Errno 2] No such file or directory

I think the download zip is not updated, can you please update it?
I am willing to see this module in action ;)

**Comment by blabberer** [comment]
i get an access denied 403 error when trying to open the url in android browser 
any ideas how to move ahead 
windows 7 sp1  and samsung mobile  
pip install virtual-touchpad didn't install it properly it wanted FCNTL module which isnt available for windows it seems 

so git cloned , downloaded the dependencies (bottle ..... pywin32 for python version 2.7) and ran 
python setup.py install 

this creates an egg file in c:\Python27\Lib\Site-packages  
(because it is not a folder but an archive  and error is thrown when doing LoadImage (icon ) it cant find the icon file  
though it doesnt hinder the starting of the server 
i cannot connect to it 

any pointers regarding what am i missing would be great

**Comment by moses-palmer** [comment]
I have tested to install using both *pip* and *git clone* and experience the same issues.

A temporary workaround for you is to open *http://192.168.43.2:16080/index.xhtml* instead, or to run the application from the repo directory by issuing the following commands in a command window:

    set PYTHONPATH=lib
    python -m virtualtouchpad

When running *virtual-touchpad* from the repo directory, the advertised *URL* also works.

I will need to update the packaging---the wheel available on *PyPi* supports only *Linux*, despite being marked as cross-platform---and support proper *Windows* packages.

**Comment by blabberer** [comment]
Thanks  moses for the reply 
yes i searched the directory  yesterday for index.html found this xhtml (6 of them including some min.xhtml whose src seems to be for non touch devices i was able to open two pages index and index.min.xhtml 
one of them opens a page with nothing visible on the top and a black box in the bottom (index.xhtml)
other opens a page which has only a question mark in the right top corner and other features similar to the earlier on (index.min.xhtml)

if i open both the url in the same pc that runs the server  i get a  your browser does not support touch events page  
any ideas ? 
should i try installing opera in the mobile ? 

lenovas shareit seems to flip the powerpoint slides from a mobile so in theory i should be able to get this touchpad working 
regards

**Comment by moses-palmer** [comment]
The **.min.xhtml* files are just minified and inlined versions of the
non-minified files.

Have you tested whether the track pad works? Upon successful launch, you
will see a white bar at the top of the window and most of the screen
covered by the actual track pad. Dragging your finger across the dark area
should move the pointer on screen. If you flip your mobile to landscape, a
keyboard will be displayed.

What *Android* web browser do you use? I have tested it only on *Chrome*.
It is supposed to detect missing featured though, so an error message
should be displayed if the browser is not supported.

2016-01-25 5:48 GMT+01:00 blabberer <notifications@github.com>:

**Comment by blabberer** [comment]
1) yes i see the white bar and black trackpad portion on the android browser 
2) the white bar appears to have a few sensitive points (squares that get highlighted like buttons)
3) those button like highlights appear to do nothing 
4)the trackpad does not move the mouse pointer 
5) pinch zoom  or drag nothing appears to operate 

Created by using HTTPNetworkSniffer

`Host Name	192.168.43.2:16080`
`Method	GET`
`Path	/index.xhtml`
`User Agent	Mozilla/5.0 (Linux; U; Android 2.3.6; en-gb; GT-S6102 Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1`
`Response Code	200`
`Response String	OK`
`Content Type	application/xhtml+xml`
`Referer`	 
`Content Encoding`	 
`Transfer Encoding	`
`Server	` 
`Content Length	6095`
`Connection	` 
`Cache Control	` 
`Location	 `
`Server Time	1/25/2016 12:45:10 PM`
`Expiration Time	` 
`Last Modified Time	1/23/2016 12:14:06 PM`
`Cookie	` 
`Client Address	192.168.43.1:51328`
`Server Address	192.168.43.2:16080`
`Request Time	00:00:11.876`
`Response Time	384 ms`
`URL	http://192.168.43.2:16080/index.xhtml `

**Comment by moses-palmer** [comment]
This appears to be three simultaneous issues:
  1. Installing from *PyPi* does not work on *Windows*.
  2. When installing using `setup.py` on *Windows*, the *systray icon* fails to load.
  3. The application does not appear to work on your browser.

I just release *0.12.4* which addresses the two first issues: the dependencies now correctly depend on the current platform, and the icon file can be loaded even when running the wheel.

Regarding issue 3: Do you use the build-in *Android Web Browser*? You appear to have a rather old version of *Android* running, and the built in browser may not be supported. Have you tried using *Chrome* or another browser from the *Play Store*?

**Comment by blabberer** [comment]
1) yes using the inbuilt browser on an old samsung duos 
2) no i haven't installed chrome yet.
3) i had opera earlier on this dump but uninstalled it to install candy crush or some other silly stuff like that on popular demand :) 
4) will check if i can install chrome on this or opera again and revert back
5) thanks for the release will check them out too

**Comment by blabberer** [comment]
installed opera but it can't parse the xhtml (missing end tag on line 5 reparse as html ? error) 
i cant get chrome to install on this phone 
in the meantime tried this with another phone (redmi2) and the trackpad and keyboard works nicely thank you for the updates
